# Generated by Django 5.2.4 on 2026-01-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(help_text='Region name in Bulgarian (e.g., София, Пловдив)', max_length=100, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Shipping cost in BGN', max_digits=6)),
                ('is_active', models.BooleanField(default=True, help_text='Is this rate currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shipping Rate',
                'verbose_name_plural': 'Shipping Rates',
                'ordering': ['region'],
            },
        ),
    ]
