# Generated by Django 5.2.4 on 2026-01-16 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_product_options_product_description_bg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Discount code (e.g., MARIA10)', max_length=50, unique=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Percentage discount (e.g., 10.00 for 10%)', max_digits=5)),
                ('active', models.BooleanField(default=True, help_text='Is this code currently active?')),
                ('valid_from', models.DateTimeField(help_text='Code valid from this date')),
                ('valid_to', models.DateTimeField(help_text='Code valid until this date')),
                ('usage_limit', models.IntegerField(blank=True, help_text='Maximum uses (leave blank for unlimited)', null=True)),
                ('times_used', models.IntegerField(default=0, help_text='Number of times code has been used')),
                ('created_by', models.CharField(blank=True, help_text='Influencer name or campaign', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Discount Code',
                'verbose_name_plural': 'Discount Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('customer_name', models.CharField(help_text='Full name', max_length=200)),
                ('customer_email', models.EmailField(help_text='Email for order confirmation', max_length=254)),
                ('customer_phone', models.CharField(help_text='Phone number', max_length=20)),
                ('shipping_address', models.TextField(help_text='Street address')),
                ('shipping_city', models.CharField(help_text='City', max_length=100)),
                ('shipping_postal_code', models.CharField(help_text='Postal code', max_length=20)),
                ('shipping_region', models.CharField(blank=True, help_text='Region/Oblast', max_length=100)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Before shipping and discount', max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, help_text='Final amount paid', max_digits=10)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_code', models.ForeignKey(blank=True, help_text='Discount code used for this order', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.discountcode')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Product name at time of order', max_length=200)),
                ('product_price', models.DecimalField(decimal_places=2, help_text='Price at time of order', max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
