# Generated by Django 5.2.4 on 2026-01-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Product name (e.g., 'Drizzle', 'Sizzle')", max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of the name', unique=True)),
                ('description', models.TextField(help_text='Short product description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in dollars', max_digits=10)),
                ('image', models.ImageField(blank=True, help_text='Main product image', null=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True, help_text='Show this product on the website?')),
                ('featured', models.BooleanField(default=False, help_text='Show on homepage?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-featured', 'name'],
            },
        ),
    ]
