# Generated by Django 5.2.4 on 2026-01-15 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-featured', 'name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='description_bg',
            field=models.TextField(blank=True, help_text='Full product description in Bulgarian'),
        ),
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(default=0, help_text='Stock quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_bg',
            field=models.CharField(blank=True, help_text='Product name in Bulgarian', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('finishing', 'Finishing Oil'), ('cooking', 'Cooking Oil'), ('bundle', 'Gift Box')], default='finishing', help_text='Type of product', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, help_text='Short tagline in English', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_bg',
            field=models.CharField(blank=True, help_text='Short tagline in Bulgarian', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Full product description in English'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text="Product name in English (e.g., 'ZLATO Finishing')", max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in BGN (Bulgarian Lev)', max_digits=10),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Additional product image', upload_to='products/gallery/')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for SEO', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order (0 = first)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['order', 'id'],
            },
        ),
    ]
